import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const acidsMetals: Topic = {
  id: "acids-metals",
  title: "Acids, Bases & Metals",
  subject: "Chemistry",
  icon: "⚗️",
  summary: "The pH scale, neutralisation and the reactivity series.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
