import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const chemicalReactions: Topic = {
  id: "chemical-reactions",
  title: "Chemical Reactions",
  subject: "Chemistry",
  icon: "🔥",
  summary: "How new substances form, and the signs of a reaction.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
