import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const digestion: Topic = {
  id: "digestion",
  title: "Food & Digestion",
  subject: "Biology",
  icon: "🍎",
  summary: "A balanced diet and how the gut breaks down food.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
