import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const elementsCompoundsMixtures: Topic = {
  id: "elements-compounds-mixtures",
  title: "Elements, Compounds & Mixtures",
  subject: "Chemistry",
  icon: "🧪",
  summary: "The building blocks of all matter and how to separate them.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
