import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const periodicTable: Topic = {
  id: "periodic-table",
  title: "The Periodic Table",
  subject: "Chemistry",
  icon: "⚛️",
  summary: "How elements are organised into groups and periods.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
