import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const photosynthesis: Topic = {
  id: "photosynthesis",
  title: "Plants & Photosynthesis",
  subject: "Biology",
  icon: "🌱",
  summary: "How green plants make their own food from light.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
