import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const respiration: Topic = {
  id: "respiration",
  title: "Respiration",
  subject: "Biology",
  icon: "🫁",
  summary: "How living cells release energy from glucose.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
