import type { Topic } from "../types";

// STUB — full content is generated by a content agent. Schema-valid placeholder.
export const sound: Topic = {
  id: "sound",
  title: "Sound",
  subject: "Physics",
  icon: "🔊",
  summary: "How sound waves travel, and pitch and loudness.",
  intro: "Content for this topic is being prepared.",
  guide: [{ id: "coming-soon", heading: "Coming soon", body: "This guide is being written." }],
  mnemonics: [],
  examMistakes: [],
  misconceptions: [],
  expertDebates: [],
  realWorld: [],
  flashcards: [],
  mustKnow: [],
  videos: [],
  quiz: { mcq: [], qa: [] },
  questionBank: { mcqPapers: [], qaPapers: [] },
};
