import type { ComprehensiveExam } from "./types";

// STUB — full content generated by a content agent.
// 4 MCQ papers (50 each) + 4 written papers (50 each) spanning all topics.
export const COMPREHENSIVE: ComprehensiveExam = {
  mcqPapers: [],
  qaPapers: [],
};
